import type { Config } from "@netlify/edge-functions";

export default async function (request: Request) {
  console.log('called')
  const redirectMap = {
    "/docs/atomsphere/integration/connectors/int-building_your_own_custom_connector_b65f74b0-4946-4a63-b082-68587a7a4814/" : "https://developer.boomi.com/docs/category/getting-started-with-connectors-development",
    "/docs/atomsphere/integration/connectors/int-connector_sdk_artifacts_72c6deee-1376-4f0b-b1db-371077460df2/" : "https://developer.boomi.com/docs/Connectors/ConnectorSDK/Connector_sdk_artifacts",
    "/docs/atomsphere/integration/connectors/r-atm-data_type_mappings_040c63aa-1964-404d-8172-08e0bd183c24/" : "https://developer.boomi.com/docs/Connectors/ConnectorSDK/Data_type_mappings",
    "/docs/atomsphere/integration/connectors/int-custom_connector_architecture_and_components_dad3e913-e94e-4b29-8e44-89aa475b09b8/" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/ConnectorArchitecture/Connector_architecture_and_components",
    "/docs/Atomsphere/Integration/Connectors/int-Connector_configuration_file_70f4adaf-045f-4854-a1bb-d21611bc8c94" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/ConnectorArchitecture/Connector_configuration_file",
    "/docs/Atomsphere/Integration/Connectors/int-Describing_the_capabilities_of_a_custom_connector_596e92e5-bcf4-4a19-926c-42ffd33799ac" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/ConnectorArchitecture/Connector_descriptor_file",
    "/docs/Atomsphere/Integration/Connectors/int-Setting_up_the_custaom_connector_development_environment_fc365e19-1048-408e-82e3-8d33ed4e9acb" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Setting_up_connector_development_environment",
    "/docs/Atomsphere/Integration/Connectors/int-Creating_a_local_custom_connector_project_cac4d05d-b506-4006-b77d-8d2a26febcee" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Creating_local_connector_project",
    "/docs/Atomsphere/Integration/Connectors/int-Creating_connector_project_Gradle_2bf60de2-e4d9-4b0b-ba7d-fd9cd0c9d68f" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Creating_local_connector_project?localProjectType=gradle",
    "/docs/Atomsphere/Integration/Connectors/int-Creating_connector_project_Maven_3ad403bc-9053-493c-8fd7-8ac20ca9c2f4" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Creating_local_connector_project?localProjectType=maven",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_connector_70111fd1-18e4-49f9-9023-a25699d09890" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Implementing_connector",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_custom_connector_operations_8d112613-21c5-456a-9484-c9415b5d61dd" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Implementing_connector_operations",
    "/docs/Atomsphere/Integration/Connectors/int-Connector_sdk_implementing_the_listen_operation_d12b4b57-70cb-497e-a6d2-b788b113ece4" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Listen_operation",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_query_operation_533351b5-db33-49b1-8734-74ee44317952" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Query_operation",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_query_operation_field_selection_sorting_and_filtering_ad760076-3a1c-4738-ae99-4c2c6f4269a0" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Field_selection_sorting_and_filtering",
    "/docs/Atomsphere/Integration/Connectors/int-Producing_query_and_execute_output_documents_332b1f24-a9dc-4e60-ba81-7089d5b8d80e" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Producing_query_and_execute_output_documents",
    "/docs/Atomsphere/Integration/Connectors/int-Legacy_filter_support_prior_to_version_1_1_0_658dc6eb-11eb-4622-9a6a-1d67e78b2e52" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Legacy_filter_support_prior_to_version_1_1_0",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_connection_29d6328d-89cb-47b8-aaf5-fdb8075b70f8" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingConnection/Implementing_connection",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_browser_377e6520-c919-46b3-a2f0-bbd23484eafb" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Implementing_browser",
    "/docs/Atomsphere/Integration/Connectors/int-implementing_the_listenconnector_interface_3b857855-6f31-46da-b3d2-401b862f13d1" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Implementing_listenconnector_interface",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_conditional_fields_668bced0-6b48-4964-ad74-6b0d206e5b1d" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Implementing_conditional_fields",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_secure_listen_2621b6d0-9f5a-4023-9cf7-1cc9d21be774" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/SecureListen/Secure_listen",
    "/docs/Atomsphere/Integration/Connectors/int-configuring_an_atom_cloud_for_secure_listen_9cb149d8-3522-4f81-8825-f7a09d1c032a" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/SecureListen/Configuring_an_atom_cloud_for_secure_listen",
    "/docs/Atomsphere/Integration/Connectors/int-configuring_an_atom_cloud_attachment_for_secure_listen_e76c60be-f083-403e-a5dc-52b492d156bf" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/SecureListen/Configuring_an_atom_cloud_attachment_for_secure_listen",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_singleton_listen_operations_40678ef6-4f4f-4566-b0d2-ad2dd6f81dab" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Singleton_listen_operations",
    "/docs/Atomsphere/Integration/Connectors/int-Debugging_and_testing_your_custom_connector_b15bf92d-2e4f-4ad4-9efa-9a25379aa7b6" : "https://developer.boomi.com/docs/Connectors/Testing_connector",
    "/docs/Atomsphere/Integration/Connectors/int-Versioning_and_releasing_your_custom_connector_caa33ca5-158f-4214-9934-724f4511185c" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Versioning_and_releasing_connector",
    "/docs/Atomsphere/Integration/Connectors/c-atm-Connector_packaging_d2e1610a-984a-4895-a643-663afab61602" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Packaging_connector",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Adding_a_connector_group_e5e5b942-affc-4f5c-b070-72aeb386a900" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Adding_connector_group",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Adding_a_version_to_a_connector_group_b38975ce-3b58-4cbf-ac9d-575879f00e40" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Adding_version_to_connector_group",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Adding_a_connector_to_a_connector_group_874e1e86-139b-44b3-89a7-79a39cc4b3a5" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Adding_connector_to_connector_group",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Changing_the_display_name_of_a_connector_3f76f6cc-e5a1-4f30-95ed-c13f6294fe4d" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Changing_display_name_of_a_connector",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Changing_the_version_or_releasing_a_connector_bae54b32-3c4e-4dbe-ae9c-2b5eb4fbb1ec" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Changing_version_or_releasing_a_connector",
    "/docs/Atomsphere/Integration/Connectors/t-atm-Changing_a_connectors_visibility_to_hidden_6c860e18-f4e3-4a83-bf94-ceef6516d666" : "https://developer.boomi.com/docs/Connectors/DeployConnectors/Changing_a_connectors_visibility_to_hidden",
    "/docs/Atomsphere/Integration/Connectors/int-Enabling_unapproved_listeners_to_run_in_a_private_Atom_Cloud_acb99cc2-b81c-4a6a-8ad9-0df7ce90c0fe" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/Enabling_unapproved_listeners_in_private_atom_clouds",
    "/docs/atomsphere/integration/connectors/int-custom_connector_design_considerations_and_best_practices_99466f21-3ae0-44b0-95ba-810140bf7b0f" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Connector_design_considerations_and_best_practices",
    "/docs/Atomsphere/Integration/Connectors/int-Connector_Development_FAQ_b6bd6fef-e672-4071-931f-9bf58db31fa3" : "https://developer.boomi.com/docs/Connectors/Connector_Development_FAQ",
    "/docs/atomsphere/integration/connectors/c-atm-soap_framework_cookbook_318a50d7-b539-4298-87d1-d5ae0de5e066/" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_cookbook",
    "/docs/Atomsphere/Integration/Connectors/c-atm-SOAP_Framework_recipes_Manipulating_data_08cebefe-7c6f-4743-940f-d0439466c1aa" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_recipes_Manipulating_data",
    "/docs/Atomsphere/Integration/Connectors/c-atm-SOAP_Framework_recipes_Manipulating_metadata_f16f32c0-5e82-4e8a-966a-da3c197ff364" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_recipes_Manipulating_metadata",
    "/docs/Atomsphere/Integration/Connectors/c-atm-Protected_WSDL_retrieval_0dad8384-0c81-4fa6-87fc-2752495778e5" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/Protected_WSDL_retrieval",
    "/docs/Atomsphere/Integration/Connectors/c-atm-WSDL_inclusion_in_the_connector_archive_8f9d8514-b98f-4818-bfee-854cb0401e51" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/WSDL_inclusion_in_the_connector_archive",
    "/docs/Atomsphere/Integration/Connectors/c-atm-SOAP_Framework_recipes_Miscellaneous_46bbbe80-dfd9-4083-92e9-9c4f6f51cc55" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_recipes_Miscellaneous",
    "/docs/Atomsphere/Integration/Connectors/c-atm-SOAP_Framework_recipes_Other_operations_9ff7815a-e2c8-4513-94c5-8c42464a3127" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_recipes_Other_operations",
    "/docs/Atomsphere/Integration/Connectors/c-atm-Browsing_support_implementation_2fc5152b-b45f-48ba-84c2-151fbe4803b1" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/Browsing_support_implementation",
    "/docs/Atomsphere/Integration/Connectors/c-atm-Implement_the_UPDATE_Operation_bf403daa-14f3-41f0-a527-21719d11ecf3" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/Implement_UPDATE_Operation",
    "/docs/Atomsphere/Integration/Connectors/c-atm-SOAP_Framework_recipes_Security_d83d3e8c-85c8-4b6b-93ee-3d7178698de3" : "https://developer.boomi.com/docs/Connectors/SOAPCookBook/SOAP_Framework_recipes_Security",
    "/docs/atomsphere/integration/connectors/int-custom_connector_reference_a0faa5c3-d385-4486-a805-93336b3293db/" : "https://developer.boomi.com/docs/category/connectors-development-reference",
    "/docs/Atomsphere/Integration/Connectors/int-Custom_connector_requirements_for_public_release_ff660fa4-8342-46c2-97fb-9b697f9b3ce6" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/Connector_requirements_for_public_release",
    "/docs/Atomsphere/Integration/Connectors/int-Including_additional_information_and_metadata_for_document_tracking_934ad44f-4f66-434c-82ca-cb3063efa325" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/Including_additional_information_and_metadata_for_document_tracking",
    "/docs/Atomsphere/Integration/Connectors/int-Resource_management_for_data_streams_b2478ab3-079a-4d16-83fb-57d8583b6bf5" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/ResourceManagement/Resource_management_for_data_streams",
    "/docs/Atomsphere/Integration/Connectors/int-Proper_resource_management_examples_c2aec241-898c-48db-a5b5-d73aba689741" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/ResourceManagement/Proper_resource_management_examples",
    "/docs/Atomsphere/Integration/Connectors/int-Improper_resource_management_examples_705f3a01-2663-402c-898f-2ffe40a165c1" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/ResourceManagement/Improper_resource_management_examples",
    "/docs/Atomsphere/Integration/Connectors/int-Custom_connector_cloud_permissions_4cc29d66-ff65-40a5-aa0c-02bcf21ccd85" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/Connector_cloud_permissions",
    "/docs/Atomsphere/Integration/Connectors/int-Entering_custom_connector_publisher_information_2230b370-615e-4b69-b703-82a68356c92b" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/Entering_connector_publisher_information",
    "/docs/Atomsphere/Integration/Connectors/int-Connector_Deployment_API_a6a433ea-6020-4719-b56b-dfe081a3a4f8" : "https://developer.boomi.com/api/connectorgroup#section/Introduction-to-Boomi-integration-connectors",
    "/docs/Atomsphere/Integration/Connectors/int_Create_connector_group_6601ad0c-50c0-4e6c-8426-127cc5118aa1" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Group",
    "/docs/Atomsphere/Integration/Connectors/int_Delete_connector_group_547b8a71-c47a-496f-93b9-879a3bf28343" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Group/operation/DeleteConnectorGroup",
    "/docs/Atomsphere/Integration/Connectors/int_Retrieve_connector_group_8c7d975e-dc14-4cf0-8de9-599989ed1495" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Group/operation/GetConnectorGroup",
    "/docs/Atomsphere/Integration/Connectors/int_Create_connector_classification_54ee4cd4-18ed-4aa1-bd0d-e433dffc50cc" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Classification/operation/CreateConnectorClassification",
    "/docs/Atomsphere/Integration/Connectors/int_Retreive_connector_groups_with_classifications_c9237f72-5aef-487d-bcb2-74e3a6d1ccfa" : "https://developer.boomi.com/api/connectorgroup/#tag/Connector-Group/operation/QueryConnectorGroupQuery",
    "/docs/Atomsphere/Integration/Connectors/int_Delete_unused_connector_classification_960a19a3-2e3f-45b9-92ad-4fe3cda32e5c" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Classification/operation/DeleteConnectorClassification",
    "/docs/Atomsphere/Integration/Connectors/int-Create_new_connector_version_c89ccf6c-a3ce-45a8-a4b2-d4453e6c0768" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Version/operation/CreateConnectorVersion",
    "/docs/Atomsphere/Integration/Connectors/int-Retrieve_connector_versions_b29a34aa-bf3b-404f-a0da-60fa470faf88" : "https://developer.boomi.com/api/connectorgroup/#tag/Connector-Version/operation/QueryConnectorVersionQuery",
    "/docs/Atomsphere/Integration/Connectors/int-Delete_connector_version_00708e0f-cd1b-4255-93de-61cdc111d222" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Version/operation/DeleteConnectorVersion",
    "/docs/Atomsphere/Integration/Connectors/int-Autoconfigure_from_connector_archive_ef8316b4-c5d4-4d46-8bab-98fba18e961a" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Archive",
    "/docs/Atomsphere/Integration/Connectors/int-Validate_descriptor_file_47c0d66d-d38f-4dd2-b50a-dc6c6d357c5f" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Descriptor-Validation",
    "/docs/Atomsphere/Integration/Connectors/int-Submit_connector_version_review_request_f503c645-587f-4e01-bf63-10e7a401c0ce" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Version-Review",
    "/docs/Atomsphere/Integration/Connectors/int-Cancel_pending_connector_version_review_request_d4a39bfa-9bc6-41ac-8539-89c04b2a0afa" : "https://developer.boomi.com/api/connectorgroup/#tag/Connector-Version-Review/operation/DeleteConnectorVersionReview",
    "/docs/Atomsphere/Integration/Connectors/int-Submit_connector_visibility_change_request_77dbc96c-ca94-4506-9c38-d524459605e6" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Visibility",
    "/docs/Atomsphere/Integration/Connectors/int-Cancel_connector_visibility_change_request_db3d9343-0941-4cdf-af21-c9d0c212fb10" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Visibility/operation/UpdateConnectorVisibility",
    "/docs/Atomsphere/Integration/Connectors/int-Create_version_change_request_e6a7e409-810c-4ed1-a5d7-db9e491e8ae7" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Version-Change/operation/CreateConnectorVersionChange",
    "/docs/Atomsphere/Integration/Connectors/int-Cancel_pending_version_change_request_00351b3a-932a-45f2-9a7e-e193576549c6" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Version-Change/operation/UpdateConnectorVersionChange",
    "/docs/Atomsphere/Integration/Connectors/int-Cancel_pending_release_public_or_private_59fbf691-6f56-48c9-9883-9e8a5287d839" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Pending-Release/operation/UpdateConnectorPendingRelease",
    "/docs/Atomsphere/Integration/Connectors/r-atm-Changelog_for_the_Connector_SDK_c2c83f82-b7af-474f-be28-a3480a50e5c9" : "https://developer.boomi.com/docs/Changelog/Changelog_connector_sdk",
    "/docs/Atomsphere/Integration/Connectors/int-Intro_SDK_Development_1d83ef2b-d69a-4016-a806-e78d9cb42a68" : "https://developer.boomi.com/docs/Connectors/ConnectorSDK/Connector_sdk_overview",
    "/docs/Atomsphere/Integration/Connectors/int-Setting_up_the_custom_connector_development_environment_fc365e19-1048-408e-82e3-8d33ed4e9acb" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Setting_up_connector_development_environment",
    "/docs/Atomsphere/Integration/Connectors/int-Building_connector_Gradle_10125e61-3eb0-49bc-985e-7f428e52796c" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Creating_local_connector_project?localProjectType=gradle",
    "/docs/Atomsphere/Integration/Connectors/int-Building_connector_Maven_f9440fee-4543-4dbb-b96f-b8814aedbcd1" : "https://developer.boomi.com/docs/Connectors/GettingStartedWithConnectorDevelopment/Creating_local_connector_project?localProjectType=maven",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_authentication_for_a_custom_connector_fac97f60-2ae7-4933-982c-d87126c4e4c8" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingConnection/Implementing_authentication_for_connector",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_test_connection_d902ac7d-a55c-4886-bc3d-27ce075276c8" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingConnection/Implementing_test_connection",
    "/docs/Atomsphere/Integration/Connectors/Proprietary_data_formats_7f97c001-1425-4d1b-8ed0-ca6ad2f27855" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Proprietary_data_formats",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_get_operation_58e6bca0-ac4f-4db7-861b-a48795097953" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Implementing_connector_operations#get",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_create_operation_7723e5ce-4383-4366-ab41-4bb573976088" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Implementing_connector_operations#create",
    "/docs/Atomsphere/Integration/Connectors/int-Implementing_the_update_operation_3e866db8-3499-4d42-a539-b7021b5ccf2c" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/ImplementingOperation/Implementing_connector_operations#update",
    "/docs/Atomsphere/Integration/Connectors/int-Other_ways_to_release_a_resource_7ae00b0b-df21-4336-a551-bcaf32421058" : "https://developer.boomi.com/docs/Connectors/ConnectorDevelopmentReference/ResourceManagement/Other_ways_release_resource",
    "/docs/Atomsphere/Integration/Connectors/Using_the_SOAP_Framework_to_build_a_custom_connector_bc320216-a892-4704-8d5d-138a4c5bf46b" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Developing_connector?framework=SOAP",
    "/docs/Atomsphere/Integration/Connectors/int-Connector_Management_API_4fabae42-7194-4cef-8284-a2d333ff594c" : "https://developer.boomi.com/api/connectorgroup",
    "/docs/Atomsphere/Integration/Connectors/int-Submit_change_connector_metadata_request_c7412be3-6c21-4645-bdb9-68ee9cbc9a82" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Metadata/operation/CreateConnectorMetadata",
    "/docs/Atomsphere/Integration/Connectors/int-Cancel_change_connector_metadata_request_871e6655-c332-4a18-bbe1-700101b7baf5" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Metadata/operation/UpdateConnectorMetadata",
    "/docs/Atomsphere/Integration/Connectors/int-Create_Connector_Icon_99cd1fea-49d1-48d1-b7a1-c28847db2c36" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Icon/operation/CreateConnectorIcon",
    "/docs/Atomsphere/Integration/Connectors/int-Retrieve_connector_icon_d53ef4cd-0a9b-4007-947b-ed37ae690297" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Icon/operation/GetConnectorIcon",
    "/docs/Atomsphere/Integration/Connectors/int-Delete_connector_icon_7a460ec0-50ba-40bd-b866-9fc70d98b1b8" : "https://developer.boomi.com/api/connectorgroup#tag/Connector-Icon/operation/DeleteConnectorIcon",
    "/atomsphere/GUID-B65F74B0-4946-4A63-B082-68587A7A4814.html" : "https://developer.boomi.com/docs/category/getting-started-with-connectors-development/",
    "/docs/Atomsphere/Integration/AtomSphere%20API/atm-Account_Cloud_Attachment_Quota_object_5a0d18f7-1474-4374-9160-7aa23d64442e" : "https://developer.boomi.com/api/platformapi#tag/AccountCloudAttachmentQuota",
    "/docs/Atomsphere/Integration/AtomSphere%20API/atm-Download_shared_web_server_log_operation" : "https://developer.boomi.com/docs/APIs/PlatformAPI/MissingInOpenAPI/Download_shared_web_server_log",
    "/docs/Atomsphere/Integration/AtomSphere%20API/c-atm-API_connectors_5bee2100-69e3-4d14-93d6-a33acdb47863" : "https://developer.boomi.com/api/platformapi#section/Introduction/API-connectors",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Account_Cloud_attachment_properties_object_936f1091-9d5c-4069-9e02-6d70bdd0fee3" : "https://developer.boomi.com/api/platformapi#tag/AccountCloudAttachmentProperties",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-API_versioning_and_deprecation_policy_3e5c39ce-d73b-42b2-a6fd-c8393c931229" : "https://developer.boomi.com/api/platformapi#section/Introduction/API-versioning-and-deprecation-policy",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Atom_counters_object_75e37916-cb64-4a5f-aac3-3935b4befa6f" : "https://developer.boomi.com/api/platformapi#tag/AtomCounters",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Atom_Disk_Space_object_c45412e5-6356-41c7-b3ed-63e91384edf6" : "https://developer.boomi.com/api/platformapi#tag/AtomDiskSpace",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Atom_Security_Policies_object_994e39d3-7c5d-49f7-9444-bb07931bf1d3" : "https://developer.boomi.com/api/platformapi#tag/AtomSecurityPolicies",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-AtomSphere_API_and_Partner_API_authentication_007fdf04-3454-41f8-a36d-163435193b9b" : "https://developer.boomi.com/api/platformapi#section/Introduction/Platform-API-and-Partner-API-authentication",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Bulk_UPDATE_operations_283c2a4f-2a75-4de6-95bb-2a08428ed698" : "https://developer.boomi.com/api/platformapi#section/Introduction/Bulk-UPDATE-operations",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Clear_queue_messages_operation_2236f183-2c92-4005-b85a-b151029fdda0" : "https://developer.boomi.com/api/platformapi#tag/ClearQueue",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_Atom_Attachment_object_Legacy_deployment_410826be-78da-4f46-9aad-9c9a5c91bf08" : "https://developer.boomi.com/api/platformapi#tag/ComponentAtomAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_Diff_object" : "https://developer.boomi.com/api/platformapi#tag/ComponentDiffRequest",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_Environment_Attachment_object_Legacy_c3a42b88-9fe6-4194-b5d9-fbfa1fd5c1c4" : "https://developer.boomi.com/api/platformapi#tag/ComponentEnvironmentAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_metadata_object_c2067cb5-bb9d-4033-adc2-d4707e26e75c" : "https://developer.boomi.com/api/platformapi#tag/ComponentMetadata",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_object_f622ab4a-3e72-433d-bd36-7c759a191a34" : "https://developer.boomi.com/api/platformapi#tag/Component",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Component_Reference_object_9753782d-6322-4f20-b6f2-45d058363bc7" : "https://developer.boomi.com/api/platformapi#tag/ComponentReference",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Connection_licensing_operation_a1412b83-b14d-4023-b274-b3212902f578" : "https://developer.boomi.com/api/platformapi#tag/ConnectionLicensingReport",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Connector_document_operation_c79ede7d-c4f8-4c43-83bd-516b60504870" : "https://developer.boomi.com/api/platformapi#tag/ConnectorDocument",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Connector_Type_Object_112264ae-73a3-4b12-9c50-dbc491a48daf" : "https://developer.boomi.com/api/platformapi#tag/Connector",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Deploy_component_operation_Legacy_deployment_15cd1579-ec6a-4ac4-b70e-9d92553226f0" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Deploy_component_operation_Legacy_deployment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Deploy_process_operation_Legacy_deployment_32b05e96-bf3b-4b89-832f-49c4cc19a394" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Deploy_process_operation_Legacy_deployment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Deployed_Expired_Certificate_object_a3c15b55-0619-4d97-93ce-4d26852d3f39" : "https://developer.boomi.com/api/platformapi#tag/DeployedExpiredCertificate",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Deployment_object_Legacy_deployment_e110c7cb-b0b5-4ecf-97fb-f7c1954cd9aa" : "https://developer.boomi.com/api/platformapi#tag/Deployment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Download_Atom_worker_log_operation_6556d11f-d55f-4bfc-b695-fa2d75cdfced" : "https://developer.boomi.com/api/platformapi#tag/AtomWorkerLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Download_execution_artifacts_operation_21a6956e-2d06-46e6-8dd2-e917049dbf24" : "https://developer.boomi.com/api/platformapi#tag/ExecutionArtifacts",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-EDI_Custom_Connector_Record_object_ac091ebe-318a-4e62-8a28-7a36aae4f987" : "https://developer.boomi.com/api/platformapi#tag/EdiCustomConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Environment_extensions_object_369e890b-e10e-4af2-8c5a-e342fdf80f40" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentExtensions",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Environment_Map_Extension_External_Components_object_a8c6e3aa-5a57-4240-a229-3df02259b6b7" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtensionExternalComponent",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Environment_Map_Extension_User_Defined_Function_object_4d06240a-f980-4da7-b2cc-65daa2f38ae6" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtensionUserDefinedFunction",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Environment_Map_Extension_User_Defined_Function_Summary_object_53a3ea32-6b6f-4d60-b202-4d2e964a86ee" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtensionUserDefinedFunctionSummary",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Execution_connector_object_abb28203-9946-4c03-9205-8dc95b8f3f41" : "https://developer.boomi.com/api/platformapi#tag/ExecutionConnector",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Execution_Request_object_8d574574-44fe-4f0c-a843-69bd82fff245" : "https://developer.boomi.com/api/platformapi#tag/ExecutionRequest",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Folder_object_c17270ca-c3b5-40f2-b2b4-2c95494be9d9" : "https://developer.boomi.com/api/platformapi#tag/Folder",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Generic_connector_record_object_44c06f13-c285-4153-9daa-fe95a5880d96" : "https://developer.boomi.com/api/platformapi#tag/GenericConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Get_queues_list_operation_0413faf1-d943-4a96-afcb-23db9da23403" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Get_queues_list_operation",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-HL7_Connector_Record_object_93ebd6ca-864a-41d2-92b3-c60db872ce8b" : "https://developer.boomi.com/api/platformapi#tag/HL7ConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Java_upgrade_schedule_object_8b1387a5-b820-4961-bd87-3d974f72a5b3" : "https://developer.boomi.com/api/platformapi#tag/JavaUpgrade",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-List_queues_operation_aa44856a-4f80-4560-b007-b7b88924d6ad" : "https://developer.boomi.com/api/platformapi#tag/ListQueues",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Move_queue_request_d3674fde-fe70-4880-8fe9-744fe064a294" : "https://developer.boomi.com/api/platformapi#tag/MoveQueueRequest",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Node_Offboard_object_61e50de9-5c23-42e0-b3b9-3d8f33d0b5c3" : "https://developer.boomi.com/api/platformapi#tag/NodeOffboard",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Odette_Connector_Record_Object_403b39fa-94c6-4147-93a0-20854579d828" : "https://developer.boomi.com/api/platformapi#tag/ODETTEConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-OFTP2_connector_record_object_0d40e02c-d544-4f7e-a94e-76c61f5e6204" : "https://developer.boomi.com/api/platformapi#tag/OFTP2ConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-OpenAPI_3_0_4344499b-7c43-49d4-bf13-7cd2b1263ca4" : "https://developer.boomi.com/api/platformapi#section/Introduction/OpenAPI-3.0",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Organization_Component_object_32ec2021-aa5b-4c8d-b1c3-87533c3a92f3" : "https://developer.boomi.com/api/platformapi#tag/OrganizationComponent",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Packaged_Component_Manifest_object_dbfb55a2-4f25-4db9-b42f-b97a8cd35a10" : "https://developer.boomi.com/api/platformapi#tag/PackagedComponentManifest",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Persisted_process_properties_object_d0048f97-5bf6-412f-922f-5b1ff7a7355b" : "https://developer.boomi.com/api/platformapi#tag/PersistedProcessProperties",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Process_Atom_Attachment_object_Legacy_deployment_879906dc-2bff-4195-af74-f0bcaf29febb" : "https://developer.boomi.com/api/platformapi#tag/ProcessAtomAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Process_Environment_Attachment_object_Legacy_fc4a452d-db0a-44e3-b7f5-52f2382be781" : "https://developer.boomi.com/api/platformapi#tag/ProcessEnvironmentAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Purge_Atom_data_operation_ad86e6f1-2ce5-4201-94a1-84b3ae366e58" : "https://developer.boomi.com/api/platformapi#tag/AtomPurge",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Rerun_document_operation_ee8bef81-36f8-4abd-8d1f-adeee3310254" : "https://developer.boomi.com/api/platformapi#tag/RerunDocument",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Roll_back_Java_operation_4b021f3d-68ce-4f9b-b44d-882a5617476b" : "https://developer.boomi.com/api/platformapi#tag/JavaRollback",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Runtime_Release_Schedule_object_b323e4f3-0636-4f75-83df-c38dbd536f26" : "https://developer.boomi.com/api/platformapi#tag/RuntimeReleaseSchedule",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Shared_Communication_Channel_Component_object_53fe919d-a5c7-4ca0-92a7-c3b2ea1aa0bd" : "https://developer.boomi.com/api/platformapi#tag/SharedCommunicationChannelComponent",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Tradacoms_Connector_Record_object_d4ab3b87-d479-43fd-8808-d5db8c926f91" : "https://developer.boomi.com/api/platformapi#tag/TradacomsConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Trading_Partner_Processing_Group_object_9ffcf043-4004-4e86-979b-842cad3ed3f0" : "https://developer.boomi.com/api/platformapi#tag/JavaUpgrade",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Upgrade_Java_operation_3dc45f8c-b8f8-40e5-aa5b-eb0ff2b40a11" : "https://developer.boomi.com/api/platformapi#tag/JavaUpgrade",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Valid_time_zones_d84bef04-cf62-4d27-a338-f0aabd80cc4c" : "https://developer.boomi.com/api/platformapi#section/Introduction/Valid-time-zones",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_Group_Account_object_e9175f83-a4a5-439e-bcc0-830d6627f80f" : "https://developer.boomi.com/api/platformapi#tag/AccountGroupAccount",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_Group_object_6fcc3f30-cad4-4f39-9d6c-1a684b9a1280" : "https://developer.boomi.com/api/platformapi#tag/AccountGroup",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_Group_User_Role_object_64303166-b240-465e-a3e1-371d547b913d" : "https://developer.boomi.com/api/platformapi#tag/AccountGroupUserRole",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_object_d569cb7d-0b26-43ec-81a3-01c3dd22c43b" : "https://developer.boomi.com/api/platformapi#tag/Account",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_security_for_CORS_b98840c5-72ed-400b-b0bc-b1d7da9ba240" : "https://developer.boomi.com/api/platformapi#section/Introduction/Account-security-for-CORS",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_Single_Sign-on_Configuration_object_64475875-aec9-4938-b9c5-f80d591c6770" : "https://developer.boomi.com/api/platformapi#tag/AccountSSOConfig",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_User_Federation_object_fdb078e2-7244-4dcc-9348-2551d133efd9" : "https://developer.boomi.com/api/platformapi#tag/AccountUserFederation",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Account_User_Role_object_6c67b35b-1465-4fe3-82a4-62db65efee87" : "https://developer.boomi.com/api/platformapi#tag/AccountUserRole",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-API_actions_80154e2b-888c-457f-bad5-a4e71a4b6c84" : "https://developer.boomi.com/api/platformapi",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-API_errors_9ff029af-b5f9-49ee-9109-a7fb0a0d2871" : "https://developer.boomi.com/api/platformapi#section/Introduction/API-errors",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-API_objects_and_object-based_operations_8dfcbb9e-8d54-4dad-abd4-b0b92c717d94" : "https://developer.boomi.com/api/platformapi",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-API_Usage_Count_object_2a045bb7-c456-4726-bd9e-5090e990f596" : "https://developer.boomi.com/api/platformapi#tag/ApiUsageCount",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-AS2_Connector_Record_object_a913750f-b94c-4015-b452-e8840c8e03a6" : "https://developer.boomi.com/api/platformapi#tag/AS2ConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Connection_Field_Extension_Summary_object_4923d85f-c0c9-4b6b-a50a-a655025d04ed" : "https://developer.boomi.com/api/platformapi#tag/AtomConnectionFieldExtensionSummary",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Connector_Versions_object_aac09cc1-7629-430c-a7b6-ec96c1f024f2" : "https://developer.boomi.com/api/platformapi#tag/AtomConnectorVersions",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Extensions_object_62413e08-5155-44e9-95d4-fa2079b92538" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Atom_Extensions_object",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Map_Extension_functions_39f82a12-fb0b-48ce-b3e2-6afd330471f3" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Atom_Map_Extension_functions",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Map_Extension_object_12eec498-b612-4a6b-aa8d-f1ece5581525" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Atom_Map_Extension_object",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Map_Extensions_Summary_object_c91400a1-2bd6-4356-b53e-931c211c3d11" : "https://developer.boomi.com/docs/APIs/PlatformAPI/DeprecatedAPIs/Atom_Map_Extensions_Summary_object",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_object_abe420d8-8197-4136-9066-f412ed7160f6" : "https://developer.boomi.com/api/platformapi#tag/Atom",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Atom_Startup_Properties_Object_2f3f9cf6-7e94-4b6b-826b-f21685398dbc" : "https://developer.boomi.com/api/platformapi#tag/AtomStartupProperties",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-AtomSphere_API_6730e8e4-b2db-4e94-a653-82ae1d05c78e" : "https://developer.boomi.com/api/platformapi#section/Introduction/Platform-API",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Audit_log_entries_af99944b-a521-44bb-bd81-64a419935c98" : "https://developer.boomi.com/api/platformapi#tag/AuditLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Audit_Log_object_f0f9b989-fa74-4591-bea9-f841c6a7bc3c" : "https://developer.boomi.com/api/platformapi#tag/AuditLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Audit_log_query_construction_25fa1fae-c65c-435a-a855-326912a5c791" : "https://developer.boomi.com/api/platformapi#tag/AuditLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Bulk_GET_operations_bc71e578-c8f0-4b44-b8f6-7ba19394d27e" : "https://developer.boomi.com/api/platformapi#section/Introduction/Bulk-GET-operations",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Cancel_execution_operation_c9579790-f637-4414-ab83-d9d874ce9ffd" : "https://developer.boomi.com/api/platformpartnerapi#tag/Cancel-execution-operation",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Change_listener_status_e9a82c07-5a3d-4b7c-b5a3-5b0a6f281f50" : "https://developer.boomi.com/api/platformapi#tag/Change-listener-status",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Cloud_object_3d9196dd-c9ba-4587-8d40-288f5004d075" : "https://developer.boomi.com/api/platformapi#tag/Cloud",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-CORS_Rules_for_RESTish_requests_761bbf09-3545-4de3-8899-ea1cf089d411" : "https://developer.boomi.com/api/platformapi#section/Introduction/CORS-rules-for-RESTish-requests",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Custom_Tracked_Field_object_fa361e24-b5c6-418e-87c6-8d69910eb4c8" : "https://developer.boomi.com/api/platformapi#tag/CustomTrackedField",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Deployed_Package_object_897b5068-6daa-44e4-bf04-7e25385157a8" : "https://developer.boomi.com/api/platformapi#tag/DeployedPackage",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Document_Count_Account_Group_object_df23fba1-1f5f-44d9-8e06-a0ee1cf4531a" : "https://developer.boomi.com/api/platformapi#tag/DocumentCountAccountGroup",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Document_Count_Account_object_2e494a98-3abb-40ce-ab13-158bce011684" : "https://developer.boomi.com/api/platformapi#tag/DocumentCountAccount",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Download_AS2_Artifacts_Log_operation_90107efa-8571-45de-9be9-c280679ca3ba" : "https://developer.boomi.com/api/platformapi#tag/AtomAS2Artifacts",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Download_Atom_Log_operation_3a6bbd5c-656b-470c-ab5c-c95e1e33e153" : "https://developer.boomi.com/api/platformapi#tag/AtomLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Download_Process_Log_operation_f9ad8c7f-25ba-427f-b2fd-c6d6f3739d1c" : "https://developer.boomi.com/api/platformapi#tag/ProcessLog",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-EDIFACT_Connector_Record_object_1d60bc6d-c3bc-42f0-a03f-9289b5336374" : "https://developer.boomi.com/api/platformapi#tag/EDIFACTConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Atom_Attachment_object_864c3e72-88e8-4a02-b727-127abe068a2f" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentAtomAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Connection_Field_Extension_Summary_obj_0c1454f1-48e8-4290-b8f3-2c35b04f049b" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentConnectionFieldExtensionSummary",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Map_Extension_functions_79855e90-52f6-4a7c-a855-b6c00ac9b6e4" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtension",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Map_Extension_object_dfe25a7a-eb29-4a04-8937-46ac7d0118ba" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtension",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Map_Extensions_Summary_object_7a3a0907-2dca-4f08-aa4b-444ea03b4980" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentMapExtensionsSummary",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_object_70f45cc4-5424-427b-bca4-d45cb23a15f2" : "https://developer.boomi.com/api/platformapi#tag/Environment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Environment_Role_object_ede7e269-e913-48b6-8c63-018758ebfe00" : "https://developer.boomi.com/api/platformapi#tag/EnvironmentRole",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Event_object_15da6930-cd60-4a51-8db4-9e4bdac0c670" : "https://developer.boomi.com/api/platformapi#tag/Event",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Execute_Process_operation_5515ef51-0eed-47cb-a9f1-f28383a7872c" : "https://developer.boomi.com/api/platformapi#tag/ExecuteProcess",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Execution_Count_Account_Group_object_0541e0fe-27d2-4627-bf1e-38c8f0e60f75" : "https://developer.boomi.com/api/platformapi#tag/ExecutionCountAccountGroup",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Execution_Count_Account_object_08ede80b-a571-44cc-9bdd-b960ab08d98d" : "https://developer.boomi.com/api/platformapi#tag/ExecutionCountAccount",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Execution_Record_object_55a63909-07a9-4a45-be70-743a1e69760b" : "https://developer.boomi.com/api/platformapi#tag/ExecutionRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Execution_Summary_Record_object_2a027c3b-4661-491f-a5f7-fa3f591a9f0f" : "https://developer.boomi.com/api/platformapi#tag/ExecutionSummaryRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Get_Assignable_Roles_operation_046f4cbe-db88-4d6f-a611-7ff0a0587b96" : "https://developer.boomi.com/api/platformapi#tag/Get-assignable-roles",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Installer_Token_object_8bb87600-5048-4826-b716-f0173ca8798d" : "https://developer.boomi.com/api/platformapi#tag/InstallerToken",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Integration_Pack_Atom_Attachment_object_19d9e8fa-7f93-4dc3-8ee3-0bd1161ab4e9" : "https://developer.boomi.com/api/platformapi#tag/IntegrationPackAtomAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Integration_Pack_Environment_Attachment_object_f40d47ab-7292-48b1-8254-75990b84c339" : "https://developer.boomi.com/api/platformapi#tag/IntegrationPackEnvironmentAttachment",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Integration_Pack_Instance_object_e086b09c-1232-4ea8-83ac-6cc865cfacd0" : "https://developer.boomi.com/api/platformapi#tag/IntegrationPackInstance",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Integration_Pack_object_5e7b7664-26a4-47ad-b781-3bf9e82d43db" : "https://developer.boomi.com/api/platformapi#tag/IntegrationPack",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Listener_Status_object_5135515e-cc1c-422d-a7c7-1fc36fb04607" : "https://developer.boomi.com/api/platformapi#tag/ListenerStatus",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Packaged_Component_object_66fa92c8-948f-46c6-a521-3927ab431c84" : "https://developer.boomi.com/api/platformapi#tag/PackagedComponent",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Partner_API_274f60ee-f9d3-4f2a-9ca8-9014645c697b" : "https://developer.boomi.com/api/platformapi#section/Introduction/Partner-API",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Process_object_8afff423-ea7b-4fec-9de7-2dea56eb5fb5" : "https://developer.boomi.com/api/platformapi#tag/Process",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Process_Schedules_object_24378efc-8907-42c7-b9a5-1ea349ea5af7" : "https://developer.boomi.com/api/platformapi#tag/ProcessSchedules",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Project_Schedule_Status_object_5d79b3b6-6b35-48ab-bda9-c9fa30a70c68" : "https://developer.boomi.com/api/platformapi#tag/ProcessScheduleStatus",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Provision_Partner_Customer_Account_operation_7acbd296-4176-482c-a0a8-798c996fc7a8" : "https://developer.boomi.com/docs/APIs/PlatformAPI/MissingInOpenAPI/Provision_partner_customer_account_operation",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Query_filters_dab3884d-370b-4944-8477-57453228363e" : "https://developer.boomi.com/api/platformapi#section/Introduction/Query-filters",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Query_paging_f5c7070d-9743-431b-8bf5-305bf314d307" : "https://developer.boomi.com/api/platformapi#section/Introduction/Query-paging",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Role_object_c2dcdb10-f000-443c-9e9c-a281664b6860" : "https://developer.boomi.com/api/platformapi#tag/Role",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-RosettaNet_Connector_Record_object_e6ecb6e3-68aa-420d-b852-8a40c17a2581" : "https://developer.boomi.com/api/platformapi#tag/RosettaNetConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Shared_Server_Information_object_73cc43c1-c1ff-4e94-a16e-2814804f81fe" : "https://developer.boomi.com/api/platformapi#tag/SharedServerInformation",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Shared_Web_Server_object" : "https://developer.boomi.com/api/platformapi#tag/SharedWebServer",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Throughput_Account_Group_object_05ecc77d-800e-4458-ba79-b39f6a5f94ba" : "https://developer.boomi.com/api/platformapi#tag/ThroughputAccountGroup",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Throughput_Account_object_7f00aa76-0f49-4c58-9356-bf227cc64cd6" : "https://developer.boomi.com/api/platformapi#tag/ThroughputAccount",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-Trading_Partner_object_47c8b9fd-a0db-46a9-9a18-c309f46d376e" : "https://developer.boomi.com/api/platformapi#tag/TradingPartnerComponent",
    "/docs/Atomsphere/Integration/AtomSphere%20API/r-atm-X12_Connector_Record_object_e55c2583-67ed-4601-9cce-5aacc07fa116" : "https://developer.boomi.com/api/platformapi#tag/X12ConnectorRecord",
    "/docs/Atomsphere/Integration/AtomSphere%20API/t-atm-Enabling_CORS_support_for_APIs_e5a9a820-25d7-4111-a9d4-6e38ed557614" : "https://developer.boomi.com/api/platformapi#section/Introduction/Enabling-CORS-support-for-AtomSphere-and-Partner-APIs",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Branch_object" : "https://developer.boomi.com/api/platformapi#tag/Branch",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Merge_request_object" : "https://developer.boomi.com/api/platformapi#tag/MergeRequest",
    "/docs/Atomsphere/Integration/AtomSphere%20API/int-Working_with_the_Environment_Extensions_object_aae004a9-34af-44e2-85fe-f120880e3bb9" : "https://developer.boomi.com/docs/APIs/PlatformAPI/Working_with_the_Environment_Extensions_object",    
    "/docs/Atomsphere/Integration/Connectors/int-Building_OpenAPI_connector_Gradle_DSL_47599de7-a802-44a6-b904-28646d08fcf2" : "https://developer.boomi.com/docs/Connectors/DevelopConnectors/Developing_connector?framework=OpenAPI+DSL"
  };
  const redirectMapKeys = Object.keys(redirectMap) //convert the keys (source paths) to an array
  const url = new URL(request.url) // get the url.pathname from here instead of splitting the URL
  const redirectToMatch = redirectMapKeys.findIndex(r => [r.toLowerCase(), r.toLowerCase() + '/', r.toLowerCase().replace(/\/$/, "")].includes(url.pathname.toLowerCase())) // convert everything to lowercase to match it
  if (redirectToMatch === -1) {
    return // exit from Edge Function and continue with the request as if no Edge Function was present
  }
  const redirectDestination = redirectMap[redirectMapKeys[redirectToMatch]] // this means redirectsMap['the-matched-url'] which should return the destination
  return new Response(
    `<html>
      <head>
        <meta 
          content="2; 
          url=${redirectDestination}"
          http-equiv="refresh"
        />
        <style>
          body {
              display: flex;
              justify-content: center;
              align-items: center;
              height: 100vh; /* Make sure the body takes the full height of the viewport */
              margin: 0; /* Remove default margin */
              font-size: 24px; /* Adjust the font size as needed */
              font-family: 'Poppins', sans-serif; /* Set the font family */
              color: #072B55; /* Set the text color to Boomi's brand color */
              text-align: center;
          }
      </style>
      </head>
      <body>
      This content is now on Boomi's new developer documentation website. <br /> Redirecting you now.
      </body>
    </html>`,
    {
      headers: {
        "content-type": "text/html",
      },
    }
  );
}

export const config: Config = {
  pattern: [
    '^\\/[Dd][Oo][Cc][Ss]\\/[Aa][Tt][Oo][Mm][Ss][Pp][Hh][Ee][Rr][Ee]\\/[Ii][Nn][Tt][Ee][Gg][Rr][Aa][Tt][Ii][Oo][Nn]\\/[Cc][Oo][Nn][Nn][Ee][Cc][Tt][Oo][Rr][Ss]\\/.*',
    '^\\/[Aa][Tt][Oo][Mm][Ss][Pp][Hh][Ee][Rr][Ee]\\/GUID-B65F74B0-4946-4A63-B082-68587A7A4814\\.html',
    '^\\/[Dd][Oo][Cc][Ss]\\/[Aa][Tt][Oo][Mm][Ss][Pp][Hh][Ee][Rr][Ee]\\/[Ii][Nn][Tt][Ee][Gg][Rr][Aa][Tt][Ii][Oo][Nn]\\/[Aa][Tt][Oo][Mm][Ss][Pp][Hh][Ee][Rr][Ee]%20[Aa][Pp][Ii]\\/.*'
  ]
};